config/routes.rb
Subscribem::Engine.routes.draw do
  post '/accounts', to: 'accounts#create', as: :accounts
  get '/sign_up', to: "accounts#new", as: :sign_up
  root to: 'dashboard#index'
end

app/models/subscribem/account.rb
module Subscribem
  class Account < ActiveRecord::Base
    belongs_to :owner, class_name: 'Subscribem::User'
    accepts_nested_attributes_for :owner

    attr_accessible :name, :owner_attributes, :subdomain
  end
end

app/models/subscribem/user.rb
module Subscribem
  class User < ActiveRecord::Base
    attr_accessible :email, :password_digest, :password, :password_confirmation
    has_secure_password
  end
end

app/controllers/subscribem/accounts_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class AccountsController < ApplicationController
    def new
      @account = Subscribem::Account.new
      @account.build_owner
    end

    def create
      account = Account.create(params[:account])
      env['warden'].set_user(account.owner.id, scope: :user)
      env['warden'].set_user(account.id, scope: :account)
      flash[:success] = "Your account has been successfully created."
      redirect_to subscribem.root_url(subdomain: account.subdomain)
    end
  end
end

app/controllers/subscribem/application_controller.rb
module Subscribem
  class ApplicationController < ActionController::Base
    def current_account
      if user_signed_in?
        @current_account ||= begin
          account_id = env['warden'].user(scope: :account)
          Subscribem::Account.find(account_id)
        end
      end
    end
    helper_method :current_account
    
    def current_user
      if user_signed_in?
        @current_user ||= begin
          user_id = env['warden'].user(scope: :user)
          Subscribem::User.find(user_id)
        end
      end
    end
    helper_method :current_user

    def user_signed_in?
      env['warden'].authenticated?(:user)
    end
    helper_method :user_signed_in?
  end
end

app/controllers/subscribem/dashboard_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class DashboardController < ApplicationController
  end
end

app/helpers/subscribem/accounts_helper.rb
module Subscribem
  module AccountsHelper
  end
end

app/helpers/subscribem/application_helper.rb
module Subscribem
  module ApplicationHelper
  end
end

app/helpers/subscribem/dashboard_helper.rb
module Subscribem
  module DashboardHelper
  end
end

app/views/layouts/subscribem/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subscribem</title>
  <%= stylesheet_link_tag    "subscribem/application", :media => "all" %>
  <%= javascript_include_tag "subscribem/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>
  <% end %>
  <% flash.each do |k,v| %>
    <div class="flash <%= k %>"><%= v %></div>
  <% end %>
  <%= yield %>

</body>
</html>

app/views/subscribem/accounts/new.html.erb
<h2>Sign Up</h2>
<%= form_for(@account) do |account| %>
  <p>
  <%= account.label :name %><br/>
  <%= account.text_field :name %>
  <%= account.label :subdomain %><br/>
  <%= account.text_field :subdomain %>
  <%= account.fields_for :owner do |owner| %>
    <p>
      <%= owner.label :email %><br/>
      <%= owner.text_field :email %>
    </p>
    <p>
      <%= owner.label :password %><br>
      <%= owner.text_field :password %>
    </p>
    <p>
      <%= owner.label :password_confirmation %><br>
      <%= owner.text_field :password_confirmation %>
    </p>
  <% end %>
  </p>
  <%= account.submit %>
<% end %>

app/views/subscribem/dashboard/index.html.erb
<%= link_to "Account Sign Up", sign_up_path %>